name: Build README and Merge 'Dev' to 'Test'

on:
  push:
    branches:
      - main
      - test
      - dev
  workflow_dispatch:
  schedule:
    - cron: '8,28,48 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test'
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Update README, pull requests, and commits
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          python build_readme.py
          cat README.md
          cat md/pull_requests.md
          cat md/commits.md
          cat md/releases.md

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "readme-bot"
          git add -A
          git commit -m "feat(readme-bot): auto-update content" || exit 0
          git push

  merge_dev_to_test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git for merging
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "push-bot"

      - name: Merge 'dev' into 'test'
        run: |
          git checkout test
          git merge origin/dev --strategy-option theirs || (echo "Conflicts detected, attempting to resolve..." && git merge --abort && exit 1)
          git push origin test
